# Generated by Django 2.2.8 on 2019-12-29 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackUserPageVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=300)),
                ('view', models.CharField(max_length=400)),
                ('last_visited', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_visits', models.PositiveIntegerField(default=0)),
                ('is_service', models.BooleanField(default=False)),
            ],
        ),
    ]
