/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_DIDStoreException,
  SWIG_DIDResolveException
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_DIDStoreException, "org/elastos/did/exception/DIDStoreException" },
    { SWIG_DIDResolveException, "org/elastos/did/exception/DIDResolveException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "spvadapter.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_org_elastos_did_adapter_SPVAdapter_create(JNIEnv *jenv, jclass jcls, jstring jWalletDir, jstring jWalletId, jstring jNetwork, jstring jResolver) {
  char *walletDir = NULL;
  char *walletId = NULL;
  char *network = NULL;
  char *resolver = NULL;
  unsigned long result;
  jlong jresult = 0 ;

  (void)jenv;
  (void)jcls;

  if (jWalletDir) {
    walletDir = (char *)(*jenv)->GetStringUTFChars(jenv, jWalletDir, 0);
    if (!walletDir) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, "Invalid wallet data dir.");
      return 0;
    }
  } else {
    SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, "Invalid wallet data dir.");
    return 0;
  }

  if (jWalletId) {
    walletId = (char *)(*jenv)->GetStringUTFChars(jenv, jWalletId, 0);
    if (!walletId) {
      (*jenv)->ReleaseStringUTFChars(jenv, jWalletDir, (const char *)walletDir);
      SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, "Invalid wallet ID.");
      return 0;
    }
  } else {
    (*jenv)->ReleaseStringUTFChars(jenv, jWalletDir, (const char *)walletDir);
    SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, "Invalid wallet ID.");
    return 0;
  }

  if (jNetwork) {
    network = (char *)(*jenv)->GetStringUTFChars(jenv, jNetwork, 0);
  }

  if (jResolver) {
    resolver = (char *)(*jenv)->GetStringUTFChars(jenv, jResolver, 0);
  }

  result = (unsigned long)SpvDidAdapter_Create((char const *)walletDir,(char const *)walletId,(char const *)network,(char const*)resolver);

  if (walletDir) (*jenv)->ReleaseStringUTFChars(jenv, jWalletDir, (const char *)walletDir);
  if (walletId) (*jenv)->ReleaseStringUTFChars(jenv, jWalletId, (const char *)walletId);
  if (network) (*jenv)->ReleaseStringUTFChars(jenv, jNetwork, (const char *)network);
  if (resolver) (*jenv)->ReleaseStringUTFChars(jenv, jResolver, (const char *)resolver);

  if (result == 0) {
    SWIG_JavaThrowException(jenv, SWIG_DIDStoreException, "DID adapter initialize SPV wallet failed.");
    return 0;
  }

  return (jlong)result;
}


SWIGEXPORT void JNICALL Java_org_elastos_did_adapter_SPVAdapter_destroy(JNIEnv *jenv, jclass jcls, jlong jHandle) {
  (void)jenv;
  (void)jcls;
  SpvDidAdapter_Destroy((SpvDidAdapter *)jHandle);
}

SWIGEXPORT jboolean JNICALL Java_org_elastos_did_adapter_SPVAdapter_isAvailable(JNIEnv *jenv, jclass jcls, jlong jHandle) {
  SpvDidAdapter *handle = (SpvDidAdapter *)jHandle;
  int result;

  (void)jenv;
  (void)jcls;

  result = SpvDidAdapter_IsAvailable(handle);
  return (jboolean)(result != 0);
}

SWIGEXPORT jint JNICALL Java_org_elastos_did_adapter_SPVAdapter_createIdTransaction(JNIEnv *jenv, jclass jcls, jlong jHandle, jstring jPayload, jstring jMemo, jstring jPassword) {
  SpvDidAdapter *handle = (SpvDidAdapter *)jHandle;
  char *payload = NULL;
  char *memo = NULL;
  char *password = NULL;
  int result;

  (void)jenv;
  (void)jcls;

  if (jPayload) {
    payload = (char *)(*jenv)->GetStringUTFChars(jenv, jPayload, 0);
    if (!payload) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, "Invalid DID transaction payload.");
      return -1;
    }
  } else {
      SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, "Invalid DID transaction payload.");
      return -1;
  }

  if (jPassword) {
    password = (char *)(*jenv)->GetStringUTFChars(jenv, jPassword, 0);
    if (!password) {
      (*jenv)->ReleaseStringUTFChars(jenv, jPayload, (const char *)payload);
      SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, "Invalid payment password.");
      return -1;
    }
  } else {
    password = "";
  }

  if (jMemo) {
    memo = (char *)(*jenv)->GetStringUTFChars(jenv, jMemo, 0);
  }

  result = SpvDidAdapter_CreateIdTransaction(handle,(char const *)payload,(char const *)memo,(char const *)password);

  if (payload) (*jenv)->ReleaseStringUTFChars(jenv, jPayload, (const char *)payload);
  if (memo) (*jenv)->ReleaseStringUTFChars(jenv, jMemo, (const char *)memo);
  if (password) (*jenv)->ReleaseStringUTFChars(jenv, jPassword, (const char *)password);

  if (result < 0) {
    SWIG_JavaThrowException(jenv, SWIG_DIDStoreException, "DID adapter create ID teansaction failed.");
    return -1;
  }

  return (jint)result;
}


SWIGEXPORT jstring JNICALL Java_org_elastos_did_adapter_SPVAdapter_resolve(JNIEnv *jenv, jclass jcls, jlong jHandle, jstring jDid, jboolean jAll) {
  SpvDidAdapter *handle = (SpvDidAdapter *)jHandle;
  char *did = NULL;
  char *result = NULL;
  jstring jresult = 0;

  (void)jenv;
  (void)jcls;

  if (jDid) {
    did = (char *)(*jenv)->GetStringUTFChars(jenv, jDid, 0);
    if (!did) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, "Invalid DID parameter.");
      return 0;
    }
  } else {
      SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, "Invalid DID parameter.");
      return 0;
  }

  result = (char *)SpvDidAdapter_Resolve(handle,(char const *)did,(int)jAll);
  (*jenv)->ReleaseStringUTFChars(jenv, jDid, (const char *)did);

  if (result) {
    jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
    SpvDidAdapter_FreeMemory(handle,result);
  } else {
    SWIG_JavaThrowException(jenv, SWIG_DIDResolveException, "DID adapter try to resolve DID failed.");
    return 0;
  }

  return jresult;
}


#ifdef __cplusplus
}
#endif

