// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hive.proto

package hive

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message
type Request struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Input                string   `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d635d1ead41ba02c, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *Request) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Request) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

// The response message
type Response struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	StatusMessage        string   `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d635d1ead41ba02c, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *Response) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*Request)(nil), "hive.Request")
	proto.RegisterType((*Response)(nil), "hive.Response")
}

func init() { proto.RegisterFile("hive.proto", fileDescriptor_d635d1ead41ba02c) }

var fileDescriptor_d635d1ead41ba02c = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0x5d, 0x5d, 0xdb, 0x75, 0xa0, 0x7b, 0x18, 0x44, 0x83, 0x27, 0x29, 0x08, 0x9e, 0x16,
	0xd1, 0x5f, 0xe0, 0x4d, 0x10, 0x2f, 0x11, 0xbd, 0x96, 0x48, 0xc7, 0x36, 0x56, 0x93, 0xd8, 0x24,
	0x2d, 0xfd, 0xf7, 0x92, 0x8f, 0x9e, 0xbd, 0xe5, 0x79, 0x93, 0x67, 0x92, 0x37, 0x00, 0xbd, 0x9c,
	0xe8, 0x60, 0x46, 0xed, 0x34, 0x6e, 0xc3, 0xba, 0xe6, 0x50, 0x72, 0xfa, 0xf5, 0x64, 0x1d, 0x5e,
	0x42, 0x29, 0x8c, 0x6c, 0x06, 0x5a, 0xd8, 0xe6, 0x7a, 0x73, 0x7b, 0xc6, 0x0b, 0x61, 0xe4, 0x33,
	0x2d, 0xc8, 0xa0, 0x54, 0xe4, 0x66, 0x3d, 0x0e, 0xec, 0x38, 0x6e, 0xac, 0x88, 0xe7, 0x70, 0x2a,
	0x95, 0xf1, 0x8e, 0x9d, 0xc4, 0x3c, 0x41, 0x2d, 0x60, 0xc7, 0xc9, 0x1a, 0xad, 0x2c, 0xe1, 0x05,
	0x14, 0xda, 0xbb, 0x70, 0x24, 0xcf, 0x4c, 0x84, 0x37, 0xb0, 0xb7, 0x4e, 0x38, 0x6f, 0x9b, 0x1f,
	0xb2, 0x56, 0x74, 0x94, 0x47, 0x57, 0x29, 0x7d, 0x49, 0x61, 0xd0, 0x53, 0x10, 0x6f, 0xd8, 0xf1,
	0x4c, 0xf7, 0x5f, 0xb0, 0x7d, 0x92, 0x13, 0xe1, 0x1d, 0x54, 0x6f, 0xe6, 0x5b, 0x8b, 0xf6, 0x51,
	0xb5, 0xaf, 0xb2, 0x53, 0x58, 0x1d, 0x62, 0xc5, 0xdc, 0xe9, 0x6a, 0xbf, 0x62, 0x7a, 0x4e, 0x7d,
	0x14, 0x8c, 0x77, 0x1a, 0xe5, 0xe7, 0x12, 0x8c, 0x5e, 0xcf, 0xff, 0x1a, 0x1f, 0x45, 0xfc, 0xaf,
	0x87, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x50, 0x11, 0x24, 0x76, 0x3d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HiveClient is the client API for Hive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HiveClient interface {
	UploadAndSign(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	VerifyAndShow(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type hiveClient struct {
	cc *grpc.ClientConn
}

func NewHiveClient(cc *grpc.ClientConn) HiveClient {
	return &hiveClient{cc}
}

func (c *hiveClient) UploadAndSign(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/hive.Hive/UploadAndSign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hiveClient) VerifyAndShow(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/hive.Hive/VerifyAndShow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HiveServer is the server API for Hive service.
type HiveServer interface {
	UploadAndSign(context.Context, *Request) (*Response, error)
	VerifyAndShow(context.Context, *Request) (*Response, error)
}

// UnimplementedHiveServer can be embedded to have forward compatible implementations.
type UnimplementedHiveServer struct {
}

func (*UnimplementedHiveServer) UploadAndSign(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadAndSign not implemented")
}
func (*UnimplementedHiveServer) VerifyAndShow(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAndShow not implemented")
}

func RegisterHiveServer(s *grpc.Server, srv HiveServer) {
	s.RegisterService(&_Hive_serviceDesc, srv)
}

func _Hive_UploadAndSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiveServer).UploadAndSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hive.Hive/UploadAndSign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiveServer).UploadAndSign(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hive_VerifyAndShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiveServer).VerifyAndShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hive.Hive/VerifyAndShow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiveServer).VerifyAndShow(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hive_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hive.Hive",
	HandlerType: (*HiveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadAndSign",
			Handler:    _Hive_UploadAndSign_Handler,
		},
		{
			MethodName: "VerifyAndShow",
			Handler:    _Hive_VerifyAndShow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hive.proto",
}
