# Wallet Service
WALLET_API_GENERATE_MNEMONIC = '/1/eng/mnemonic'
WALLET_API_RETRIEVE_WALLET_FROM_MNEMONIC = '1/hd'
WALLET_API_CREATE_WALLET = '/1/createWallet'
WALLET_API_GET_BALANCE = '/1/balance/'
WALLET_API_GET_TRANSACTION = '/1/tx'
WALLET_API_GET_TRANSACTION_HISTORY = '/1/history/'
WALLET_API_CROSSCHAIN_TRANSFER = '/1/cross/m2d/transfer'

# Sidechain Service
DID_SERVICE_API_CREATE_DID = '/1/gen/did'
DID_SERVICE_API_RETRIEVE_DID = '/1/did/'
DID_SERVICE_API_SIGN = '/1/sign'
DID_SERVICE_API_VERIFY = '/1/verify'

# Hive
HIVE_API_ADD_FILE = '/api/v0/file/add'
HIVE_API_RETRIEVE_FILE = '/api/v0/file/cat?arg='
