# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import adenine_io_pb2 as adenine__io__pb2


class AdenineIoStub(object):
  """The service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Sign = channel.unary_unary(
        '/adenineio.AdenineIo/Sign',
        request_serializer=adenine__io__pb2.Request.SerializeToString,
        response_deserializer=adenine__io__pb2.Response.FromString,
        )
    self.UploadAndSign = channel.unary_unary(
        '/adenineio.AdenineIo/UploadAndSign',
        request_serializer=adenine__io__pb2.Request.SerializeToString,
        response_deserializer=adenine__io__pb2.Response.FromString,
        )
    self.VerifyAndShow = channel.unary_unary(
        '/adenineio.AdenineIo/VerifyAndShow',
        request_serializer=adenine__io__pb2.Request.SerializeToString,
        response_deserializer=adenine__io__pb2.Response.FromString,
        )
    self.DeployEthContract = channel.unary_unary(
        '/adenineio.AdenineIo/DeployEthContract',
        request_serializer=adenine__io__pb2.Request.SerializeToString,
        response_deserializer=adenine__io__pb2.Response.FromString,
        )
    self.RunEthContract = channel.unary_unary(
        '/adenineio.AdenineIo/RunEthContract',
        request_serializer=adenine__io__pb2.Request.SerializeToString,
        response_deserializer=adenine__io__pb2.Response.FromString,
        )


class AdenineIoServicer(object):
  """The service definition.
  """

  def Sign(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadAndSign(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VerifyAndShow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeployEthContract(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RunEthContract(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdenineIoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Sign': grpc.unary_unary_rpc_method_handler(
          servicer.Sign,
          request_deserializer=adenine__io__pb2.Request.FromString,
          response_serializer=adenine__io__pb2.Response.SerializeToString,
      ),
      'UploadAndSign': grpc.unary_unary_rpc_method_handler(
          servicer.UploadAndSign,
          request_deserializer=adenine__io__pb2.Request.FromString,
          response_serializer=adenine__io__pb2.Response.SerializeToString,
      ),
      'VerifyAndShow': grpc.unary_unary_rpc_method_handler(
          servicer.VerifyAndShow,
          request_deserializer=adenine__io__pb2.Request.FromString,
          response_serializer=adenine__io__pb2.Response.SerializeToString,
      ),
      'DeployEthContract': grpc.unary_unary_rpc_method_handler(
          servicer.DeployEthContract,
          request_deserializer=adenine__io__pb2.Request.FromString,
          response_serializer=adenine__io__pb2.Response.SerializeToString,
      ),
      'RunEthContract': grpc.unary_unary_rpc_method_handler(
          servicer.RunEthContract,
          request_deserializer=adenine__io__pb2.Request.FromString,
          response_serializer=adenine__io__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'adenineio.AdenineIo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
