INSERT INTO COUNTRY VALUES (1, 'USA');

INSERT INTO USER_TYPE VALUES (1, 'ADMIN');
INSERT INTO USER_TYPE VALUES (2, 'DEVELOPER');

INSERT INTO USERS VALUES (1, '101ABC' , '564732BHU', 'NEHA PATIL', 'npatil2@gmu.edu', 'GMU' ,3137424152, 'FAIRFAX', 1, 2, current_timestamp, current_timestamp);

INSERT INTO USER_API_RELATION VALUES (1, 1, '564732BHU');
INSERT INTO USER_API_RELATION VALUES (1, 1, 'KHBOsth7b3WbOTVzZqGUEhOY8rPreYFM');


