CREATE DATABASE elastos_admin;

CREATE DATABASE elastos_console;

set schema 'public';

CREATE TABLE COUNTRY(
   ID INTEGER PRIMARY KEY NOT NULL,
   NAME VARCHAR(20) NOT NULL,
	UNIQUE(ID, NAME)
);

CREATE TABLE USER_TYPE(
   ID INTEGER PRIMARY KEY NOT NULL,
   TYPE VARCHAR(20) NOT NULL,
	UNIQUE(ID, TYPE)
);

CREATE TABLE USERS(
   ID INTEGER PRIMARY KEY NOT NULL,
   USER_ID VARCHAR(20) NOT NULL,
   DID VARCHAR(50) NOT NULL,
   NAME VARCHAR(80)  NOT NULL,
   EMAIL VARCHAR(30) NOT NULL,
   ORGANIZATION VARCHAR(50),
   PHONE_NUMBER INTEGER,
   CITY VARCHAR(20) NOT NULL,
   COUNTRY INTEGER NOT NULL,
   USER_TYPE INTEGER NOT NULL,
   CREATED_ON INTEGER NOT NULL,
   LAST_LOGGED_ON INTEGER NOT NULL,
   UNIQUE(ID, DID),
   FOREIGN KEY (COUNTRY) REFERENCES COUNTRY(ID),
   FOREIGN KEY (USER_TYPE) REFERENCES USER_TYPE(ID)
);

CREATE TABLE USER_API_RELATION(
   ID INTEGER PRIMARY KEY NOT NULL,
   USER_TYPE INTEGER REFERENCES USER_TYPE(ID) NOT NULL,
   API_KEY VARCHAR(20) NOT NULL,
   UNIQUE (API_KEY)
);