# Elastos privnet - Mainchain - elastos.org
# This is an official but unsupported docker image

# alpine3.8 - use image digest for security
FROM alpine@sha256:dad671370a148e9d9573e3e10a9f8cc26ce937bea78f3da80b570c2442364406

RUN apk update
RUN apk add --no-cache curl

COPY ./ela/elastos ./ela/elastos
COPY ./ela/ela ./ela/ela
COPY ./ela/config.json ./ela/config.json 

# Create unprivileged user (running processes securely)
RUN adduser -D -g '' elauser

# Give permission to elauser for necessary folders
RUN chown -R elauser /ela

USER elauser

WORKDIR /ela

EXPOSE 20333-20338

ENTRYPOINT ["/bin/sh", "-c", "./ela"]
