# Elastos privnet - Arbiter 1 - elastos.org
# This is an official but unsupported docker image

# alpine3.8 - use image digest for security
FROM alpine@sha256:dad671370a148e9d9573e3e10a9f8cc26ce937bea78f3da80b570c2442364406

RUN apk update
RUN apk add --no-cache curl

COPY ./arbiter-1/arbiter ./arbiter-1/arbiter
COPY ./arbiter-1/elastos_arbiter ./arbiter-1/elastos_arbiter
COPY ./arbiter-1/config.json ./arbiter-1/config.json

COPY ./wallets/arbiter-1/*.dat ./arbiter-1/

# Create unprivileged user (running processes securely)
RUN adduser -D -g '' elauser

# Give permission to elauser for necessary folders
RUN chown -R elauser /arbiter-1

USER elauser

WORKDIR /arbiter-1

EXPOSE 10336
EXPOSE 10338

ENTRYPOINT ["/bin/sh", "-c", "./arbiter -p elastos"]