# Elastos privnet - Mainchain - elastos.org
# This is an official but unsupported docker image

# alpine3.8 - use image digest for security
FROM alpine@sha256:dad671370a148e9d9573e3e10a9f8cc26ce937bea78f3da80b570c2442364406

RUN apk update
RUN apk add --no-cache curl
RUN apk add --no-cache mysql-client

COPY ./api-misc/elaChain /go/src/github.com/elastos/Elastos.ORG.Misc.API/elaChain
COPY ./api-misc/config.json /go/src/github.com/elastos/Elastos.ORG.Misc.API/config.json

# Copy SQL Files
COPY ./ela-mysql/* /go/src/github.com/elastos/Elastos.ORG.Misc.API/sql-init/
RUN chmod +x /go/src/github.com/elastos/Elastos.ORG.Misc.API/sql-init/*.sql

# Create unprivileged user (running processes securely)
RUN adduser -D -g '' elauser

# Give permission to elauser for necessary folders
RUN chown -R elauser /go/src/github.com/elastos/Elastos.ORG.Misc.API

USER elauser

# Copy Start Script
COPY ./deploy_scripts/deploy-api-misc.sh /home/elauser/deploy.sh

EXPOSE 8093

# These scripts also initialize the DB
CMD sh -c "sh /home/elauser/deploy.sh && /bin/sh"

