# Elastos privnet - Wallet Service - elastos.org
# This is an official but unsupported docker image

FROM maven:3.6.0-jdk-8-alpine

COPY ./restful-services/wallet-service/base.api/target/base.api-0.0.6.jar /restful-services/base.api-0.0.6.jar

# Create unprivileged user (running processes securely)
RUN adduser -D -g '' elauser

# Give permission to elauser for necessary folders
RUN chown -R elauser /restful-services

USER elauser

EXPOSE 3307
EXPOSE 8091

ENTRYPOINT ["java", "-jar", "/restful-services/base.api-0.0.6.jar"]