# Elastos privnet - DID Sidechain - elastos.org
# This is an official but unsupported docker image

# alpine3.8 - use image digest for security
FROM alpine@sha256:dad671370a148e9d9573e3e10a9f8cc26ce937bea78f3da80b570c2442364406

RUN apk update
RUN apk add --no-cache curl

COPY ./did/elastos_did ./did/elastos_did
COPY ./did/did ./did/did
COPY ./did/config.json ./did/config.json

# Create unprivileged user (running processes securely)
RUN adduser -D -g '' elauser

# Give permission to elauser for necessary folders
RUN chown -R elauser /did

USER elauser

WORKDIR /did

EXPOSE 20604-20608

ENTRYPOINT ["/bin/sh", "-c", "./did"]

