FROM ubuntu:16.04

ARG USER_NAME=elastos
ARG USER_UID=1000
ARG USER_GID=1000

# Default password of elastos is 'developer'
# The encrypted password was generated by 'openssl passwd -1 developer'
ENV DEFAULT_PASSWORD '$1$Ezg5Gt2h$mAZfdAiRatxUVdAUp9Qkk.'

ENV LANG=C.UTF-8

RUN set -ex                                                                         && \
                                                                                       \
    echo 'Creating non-root user and group from host'                               && \
    groupadd -f -g $USER_GID $USER_NAME                                             && \
    useradd -lm -p $DEFAULT_PASSWORD -u $USER_UID -g $USER_GID $USER_NAME           && \
    usermod -aG sudo $USER_NAME                                                     && \
    echo 'D' > /etc/debian_chroot                                                   && \
    apt-get update && apt-get install -y                                               \
        sudo \
        vim \
        autoconf \
        autopoint \
        libtool \
        build-essential \
        net-tools \
        fakeroot \
        tofrodos \
        flex \
        bison \
        texinfo \
        openssl \
        git \
        gperf \
        make \
        bc \
        zip \
        gdbserver \
        bash-completion \
        cmake \
        python \
        doxygen \
        python-sphinx \
        graphviz \
        wget \
        curl \
        libssl-dev \
        libncurses5-dev                                                             && \
    curl -L -o /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py                 && \
    python /tmp/get-pip.py                                                          && \
    pip install breathe                                                             && \
    curl -L -o /tmp/flatcc-0.5.0.tar.gz https://github.com/dvidelabs/flatcc/archive/v0.5.0.tar.gz && \
    cd /tmp && tar xzvf flatcc-0.5.0.tar.gz                                         && \
    mkdir -p /tmp/flatcc-0.5.0/build/install                                        && \
    cd /tmp/flatcc-0.5.0/build/install && cmake ../.. -DFLATCC_INSTALL=on           && \
    cd /tmp/flatcc-0.5.0/build/install && make install                              && \
    rm -rf /tmp/*                                                                   && \
    rm -rf /var/lib/apt/list/*

USER elastos

VOLUME /home/elastos/Projects
WORKDIR /home/elastos/Projects
