/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elastos_spvcore_CorePeer */

#ifndef _Included_com_elastos_spvcore_CorePeer
#define _Included_com_elastos_spvcore_CorePeer
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    getAddress
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CorePeer_getAddress
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    getPort
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_com_elastos_spvcore_CorePeer_getPort
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    getTimestamp
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePeer_getTimestamp
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    setEarliestKeyTime
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeer_setEarliestKeyTime
		(JNIEnv *, jobject, jlong);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    setCurrentBlockHeight
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeer_setCurrentBlockHeight
		(JNIEnv *, jobject, jlong);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    getConnectStatusValue
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_com_elastos_spvcore_CorePeer_getConnectStatusValue
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    connect
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeer_connect
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    disconnect
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeer_disconnect
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    scheduleDisconnect
	 * Signature: (D)V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeer_scheduleDisconnect
		(JNIEnv *, jobject, jdouble);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    setNeedsFilterUpdate
	 * Signature: (Z)V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeer_setNeedsFilterUpdate
		(JNIEnv *, jobject, jboolean);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    getHost
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CorePeer_getHost
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    getVersion
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePeer_getVersion
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    getUserAgent
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CorePeer_getUserAgent
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    getLastBlock
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePeer_getLastBlock
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    getFeePerKb
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePeer_getFeePerKb
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    getPingTime
	 * Signature: ()D
	 */
	JNIEXPORT jdouble JNICALL Java_com_elastos_spvcore_CorePeer_getPingTime
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    createJniCorePeerNatural
	 * Signature: ([BIJ)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePeer_createJniCorePeerNatural
		(JNIEnv *, jclass, jbyteArray, jint, jlong);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    createJniCorePeer
	 * Signature: ([B[B[B)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePeer_createJniCorePeer
		(JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

	/*
	 * Class:     com_elastos_spvcore_CorePeer
	 * Method:    createJniCorePeerMagic
	 * Signature: (J)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePeer_createJniCorePeerMagic
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
