/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elastos_spvcore_CoreJniReference */

#ifndef _Included_com_elastos_spvcore_CoreJniReference
#define _Included_com_elastos_spvcore_CoreJniReference
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_elastos_spvcore_CoreJniReference
	 * Method:    disposeNative
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CoreJniReference_disposeNative
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
