/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elastos_spvcore_CoreTransactionInput */

#ifndef _Included_com_elastos_spvcore_CoreTransactionInput
#define _Included_com_elastos_spvcore_CoreTransactionInput
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_elastos_spvcore_CoreTransactionInput
	 * Method:    createTransactionInput
	 * Signature: ([BJJ[B[BJ)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CoreTransactionInput_createTransactionInput
		(JNIEnv *, jclass, jbyteArray, jlong, jlong, jbyteArray, jbyteArray, jlong);

	/*
	 * Class:     com_elastos_spvcore_CoreTransactionInput
	 * Method:    getAddress
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CoreTransactionInput_getAddress
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CoreTransactionInput
	 * Method:    setAddress
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CoreTransactionInput_setAddress
		(JNIEnv *, jobject, jstring);

	/*
	 * Class:     com_elastos_spvcore_CoreTransactionInput
	 * Method:    getHash
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CoreTransactionInput_getHash
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CoreTransactionInput
	 * Method:    getIndex
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CoreTransactionInput_getIndex
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CoreTransactionInput
	 * Method:    getAmount
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CoreTransactionInput_getAmount
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CoreTransactionInput
	 * Method:    getScript
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CoreTransactionInput_getScript
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CoreTransactionInput
	 * Method:    getSignature
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CoreTransactionInput_getSignature
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CoreTransactionInput
	 * Method:    getSequence
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CoreTransactionInput_getSequence
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
