/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elastos_spvcore_CorePaymentProtocolPaymentACK */

#ifndef _Included_com_elastos_spvcore_CorePaymentProtocolPaymentACK
#define _Included_com_elastos_spvcore_CorePaymentProtocolPaymentACK
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPaymentACK
	 * Method:    getCustomerMemo
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPaymentACK_getCustomerMemo
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPaymentACK
	 * Method:    getMerchantData
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPaymentACK_getMerchantData
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPaymentACK
	 * Method:    getTransactions
	 * Signature: ()[Lcom/breadwallet/core/BRCoreTransaction;
	 */
	JNIEXPORT jobjectArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPaymentACK_getTransactions
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPaymentACK
	 * Method:    getRefundTo
	 * Signature: ()[Lcom/breadwallet/core/BRCoreTransactionOutput;
	 */
	JNIEXPORT jobjectArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPaymentACK_getRefundTo
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPaymentACK
	 * Method:    getMerchantMemo
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPaymentACK_getMerchantMemo
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPaymentACK
	 * Method:    createPaymentProtocolPaymentACK
	 * Signature: ([B)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPaymentACK_createPaymentProtocolPaymentACK
		(JNIEnv *, jclass, jbyteArray);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPaymentACK
	 * Method:    serialize
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPaymentACK_serialize
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPaymentACK
	 * Method:    disposeNative
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPaymentACK_disposeNative
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
