/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elastos_spvcore_CorePaymentProtocolMessage */

#ifndef _Included_com_elastos_spvcore_CorePaymentProtocolMessage
#define _Included_com_elastos_spvcore_CorePaymentProtocolMessage
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolMessage
	 * Method:    getMessageTypeValue
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_com_elastos_spvcore_CorePaymentProtocolMessage_getMessageTypeValue
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolMessage
	 * Method:    getMessage
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolMessage_getMessage
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolMessage
	 * Method:    getStatusCode
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePaymentProtocolMessage_getStatusCode
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolMessage
	 * Method:    getStatusMessage
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CorePaymentProtocolMessage_getStatusMessage
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolMessage
	 * Method:    getIdentifier
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolMessage_getIdentifier
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolMessage
	 * Method:    createPaymentProtocolMessage
	 * Signature: ([B)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePaymentProtocolMessage_createPaymentProtocolMessage
		(JNIEnv *, jclass, jbyteArray);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolMessage
	 * Method:    createPaymentProtocolMessageFull
	 * Signature: (I[BJLjava/lang/String;[B)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePaymentProtocolMessage_createPaymentProtocolMessageFull
		(JNIEnv *, jclass, jint, jbyteArray, jlong, jstring, jbyteArray);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolMessage
	 * Method:    serialize
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolMessage_serialize
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolMessage
	 * Method:    disposeNative
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePaymentProtocolMessage_disposeNative
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
