/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elastos_spvcore_CorePaymentProtocolPayment */

#ifndef _Included_com_elastos_spvcore_CorePaymentProtocolPayment
#define _Included_com_elastos_spvcore_CorePaymentProtocolPayment
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPayment
	 * Method:    getMerchantData
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPayment_getMerchantData
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPayment
	 * Method:    getTransactions
	 * Signature: ()[Lcom/breadwallet/core/BRCoreTransaction;
	 */
	JNIEXPORT jobjectArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPayment_getTransactions
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPayment
	 * Method:    getRefundTo
	 * Signature: ()[Lcom/breadwallet/core/BRCoreTransactionOutput;
	 */
	JNIEXPORT jobjectArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPayment_getRefundTo
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPayment
	 * Method:    getMerchantMemo
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPayment_getMerchantMemo
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPayment
	 * Method:    createPaymentProtocolPayment
	 * Signature: ([B)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPayment_createPaymentProtocolPayment
		(JNIEnv *, jclass, jbyteArray);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPayment
	 * Method:    serialize
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPayment_serialize
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPayment
	 * Method:    disposeNative
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPayment_disposeNative
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolPayment
	 * Method:    initializeNative
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePaymentProtocolPayment_initializeNative
		(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
