/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elastos_spvcore_CoreTransactionOutput */

#ifndef _Included_com_elastos_spvcore_CoreTransactionOutput
#define _Included_com_elastos_spvcore_CoreTransactionOutput
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_elastos_spvcore_CoreTransactionOutput
	 * Method:    createTransactionOutput
	 * Signature: (J[B)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CoreTransactionOutput_createTransactionOutput
		(JNIEnv *, jclass, jlong, jbyteArray);

	/*
	 * Class:     com_elastos_spvcore_CoreTransactionOutput
	 * Method:    getAddress
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CoreTransactionOutput_getAddress
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CoreTransactionOutput
	 * Method:    setAddress
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CoreTransactionOutput_setAddress
		(JNIEnv *, jobject, jstring);

	/*
	 * Class:     com_elastos_spvcore_CoreTransactionOutput
	 * Method:    getAmount
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CoreTransactionOutput_getAmount
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CoreTransactionOutput
	 * Method:    setAmount
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CoreTransactionOutput_setAmount
		(JNIEnv *, jobject, jlong);

	/*
	 * Class:     com_elastos_spvcore_CoreTransactionOutput
	 * Method:    getScript
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CoreTransactionOutput_getScript
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
