/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elastos_spvcore_CorePaymentProtocolRequest */

#ifndef _Included_com_elastos_spvcore_CorePaymentProtocolRequest
#define _Included_com_elastos_spvcore_CorePaymentProtocolRequest
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    getNetwork
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_getNetwork
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    getOutputs
	 * Signature: ()[Lcom/breadwallet/core/BRCoreTransactionOutput;
	 */
	JNIEXPORT jobjectArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_getOutputs
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    getTime
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_getTime
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    getExpires
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_getExpires
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    getMemo
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_getMemo
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    getPaymentURL
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_getPaymentURL
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    getMerchantData
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_getMerchantData
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    getVersion
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_getVersion
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    getPKIType
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_getPKIType
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    getPKIData
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_getPKIData
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    getSignature
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_getSignature
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    getDigest
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_getDigest
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    getCerts
	 * Signature: ()[[B
	 */
	JNIEXPORT jobjectArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_getCerts
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    createPaymentProtocolRequest
	 * Signature: ([B)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_createPaymentProtocolRequest
		(JNIEnv *, jclass, jbyteArray);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    serialize
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_serialize
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    disposeNative
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_disposeNative
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePaymentProtocolRequest
	 * Method:    initializeNative
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePaymentProtocolRequest_initializeNative
		(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
