/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elastos_spvcore_CorePeerManager */

#ifndef _Included_com_elastos_spvcore_CorePeerManager
#define _Included_com_elastos_spvcore_CorePeerManager
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    getConnectStatusValue
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_com_elastos_spvcore_CorePeerManager_getConnectStatusValue
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    connect
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeerManager_connect
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    jniUseFixedPeer
	 * Signature: (Ljava/lang/String;I)Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_elastos_spvcore_CorePeerManager_jniUseFixedPeer
		(JNIEnv *, jobject, jstring, jint);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    getCurrentPeerName
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CorePeerManager_getCurrentPeerName
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    disconnect
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeerManager_disconnect
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    rescan
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeerManager_rescan
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    getEstimatedBlockHeight
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePeerManager_getEstimatedBlockHeight
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    getLastBlockHeight
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePeerManager_getLastBlockHeight
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    getLastBlockTimestamp
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePeerManager_getLastBlockTimestamp
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    getSyncProgress
	 * Signature: (J)D
	 */
	JNIEXPORT jdouble JNICALL Java_com_elastos_spvcore_CorePeerManager_getSyncProgress
		(JNIEnv *, jobject, jlong);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    getPeerCount
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_com_elastos_spvcore_CorePeerManager_getPeerCount
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    getDownloadPeerName
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CorePeerManager_getDownloadPeerName
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    publishTransactionWithListener
	 * Signature: (Lcom/breadwallet/core/BRCoreTransaction;Lcom/breadwallet/core/BRCorePeerManager/Listener;)V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeerManager_publishTransactionWithListener
		(JNIEnv *, jobject, jobject, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    getRelayCount
	 * Signature: ([B)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePeerManager_getRelayCount
		(JNIEnv *, jobject, jbyteArray);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    testSaveBlocksCallback
	 * Signature: (Z[Lcom/breadwallet/core/BRCoreMerkleBlock;)V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeerManager_testSaveBlocksCallback
		(JNIEnv *, jobject, jboolean, jobjectArray);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    testSavePeersCallback
	 * Signature: (Z[Lcom/breadwallet/core/BRCorePeer;)V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeerManager_testSavePeersCallback
		(JNIEnv *, jobject, jboolean, jobjectArray);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    createCorePeerManager
	 * Signature: (Lcom/breadwallet/core/BRCoreChainParams;Lcom/breadwallet/core/BRCoreWallet;D[Lcom/breadwallet/core/BRCoreMerkleBlock;[Lcom/breadwallet/core/BRCorePeer;)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CorePeerManager_createCorePeerManager
		(JNIEnv *, jclass, jobject, jobject, jdouble, jobjectArray, jobjectArray);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    installListener
	 * Signature: (Lcom/breadwallet/core/BRCorePeerManager/Listener;)V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeerManager_installListener
		(JNIEnv *, jobject, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    disposeNative
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeerManager_disposeNative
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CorePeerManager
	 * Method:    initializeNative
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_elastos_spvcore_CorePeerManager_initializeNative
		(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
