/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elastos_spvcore_CoreAddress */

#ifndef _Included_com_elastos_spvcore_CoreAddress
#define _Included_com_elastos_spvcore_CoreAddress
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_elastos_spvcore_CoreAddress
	 * Method:    createCoreAddress
	 * Signature: (Ljava/lang/String;)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CoreAddress_createCoreAddress
		(JNIEnv *, jclass, jstring);

	/*
	 * Class:     com_elastos_spvcore_CoreAddress
	 * Method:    createCoreAddressFromScriptPubKey
	 * Signature: ([B)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CoreAddress_createCoreAddressFromScriptPubKey
		(JNIEnv *, jclass, jbyteArray);

	/*
	 * Class:     com_elastos_spvcore_CoreAddress
	 * Method:    createCoreAddressFromScriptSignature
	 * Signature: ([B)J
	 */
	JNIEXPORT jlong JNICALL Java_com_elastos_spvcore_CoreAddress_createCoreAddressFromScriptSignature
		(JNIEnv *, jclass, jbyteArray);

	/*
	 * Class:     com_elastos_spvcore_CoreAddress
	 * Method:    stringify
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CoreAddress_stringify
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CoreAddress
	 * Method:    isValid
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_elastos_spvcore_CoreAddress_isValid
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CoreAddress
	 * Method:    getPubKeyScript
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_elastos_spvcore_CoreAddress_getPubKeyScript
		(JNIEnv *, jobject);

	/*
	 * Class:     com_elastos_spvcore_CoreAddress
	 * Method:    bcashDecodeBitcoin
	 * Signature: (Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CoreAddress_bcashDecodeBitcoin
		(JNIEnv *, jclass, jstring);

	/*
	 * Class:     com_elastos_spvcore_CoreAddress
	 * Method:    bcashEncodeBitcoin
	 * Signature: (Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_elastos_spvcore_CoreAddress_bcashEncodeBitcoin
		(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
