apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: privnet-wallet-service-tokensidechain
  name: privnet-wallet-service-tokensidechain
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: privnet-wallet-service-tokensidechain
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: privnet-wallet-service-tokensidechain
  name: privnet-wallet-service-tokensidechain
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: privnet-wallet-service-tokensidechain
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: privnet-wallet-service-tokensidechain
    spec:
      containers:
      - image: cyberrepublic/elastos-wallet-service:privnet-v0.6
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8080/api/1/currHeight
          failureThreshold: 5
          periodSeconds: 30
          timeoutSeconds: 120
        name: privnet-wallet-service-tokensidechain
        ports:
        - containerPort: 8080
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /home/elauser/application.properties
          name: privnet-wallet-service-tokensidechain-hostpath0
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /home/kpachhai/dev/src/github.com/tuum-tech/elastos-privnet/blockchain/restful-services/wallet/application-mainchain-token.properties
        name: privnet-wallet-service-tokensidechain-hostpath0
status: {}
