set schema 'public';

CREATE TABLE IF NOT EXISTS USERS(
   ID INTEGER PRIMARY KEY NOT NULL,
   DID VARCHAR(50) NOT NULL,
   NAME VARCHAR(80)  NOT NULL,
   EMAIL VARCHAR(30) NOT NULL,
   CREATED_ON TIMESTAMP NOT NULL,
   LAST_LOGGED_ON TIMESTAMP NOT NULL,
   UNIQUE(ID, DID)
);

CREATE TABLE IF NOT EXISTS USER_API_RELATIONS(
   ID INTEGER PRIMARY KEY NOT NULL,
   USER_ID INTEGER REFERENCES USERS(ID) NOT NULL,
   API_KEY VARCHAR(32) NOT NULL,
   UNIQUE (API_KEY)
);