set schema 'public';

CREATE TABLE IF NOT EXISTS USERS(
   ID BIGSERIAL PRIMARY KEY NOT NULL,
   DID VARCHAR(64) NOT NULL,
   CREATED_ON TIMESTAMP NOT NULL,
   LAST_LOGGED_ON TIMESTAMP NOT NULL,
   UNIQUE(ID, DID)
);

CREATE TABLE IF NOT EXISTS USER_API_RELATIONS(
   ID BIGSERIAL PRIMARY KEY NOT NULL,
   USER_ID INTEGER REFERENCES USERS(ID) NOT NULL,
   API_KEY VARCHAR(64) NOT NULL,
   UNIQUE (API_KEY)
);

CREATE TABLE IF NOT EXISTS SERVICES_LISTS(
   ID BIGSERIAL PRIMARY KEY NOT NULL,
   USER_API_ID INTEGER REFERENCES USER_API_RELATIONS(ID) NOT NULL,
   SERVICE_NAME VARCHAR(20) NOT NULL,
   LAST_ACCESS TIMESTAMP NOT NULL,
   ACCESS_COUNT INTEGER
);

GRANT SELECT, UPDATE, INSERT ON USERS TO gmu;
GRANT SELECT, UPDATE, INSERT ON USER_API_RELATIONS TO gmu;
GRANT SELECT, UPDATE, INSERT ON SERVICES_LISTS TO gmu;
