# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import adenine_io_pb2 as adenine__io__pb2


class AdenineIoStub(object):
  """The service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendRequest = channel.unary_unary(
        '/adenineio.AdenineIo/sendRequest',
        request_serializer=adenine__io__pb2.Request.SerializeToString,
        response_deserializer=adenine__io__pb2.Response.FromString,
        )


class AdenineIoServicer(object):
  """The service definition.
  """

  def sendRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdenineIoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendRequest': grpc.unary_unary_rpc_method_handler(
          servicer.sendRequest,
          request_deserializer=adenine__io__pb2.Request.FromString,
          response_serializer=adenine__io__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'adenineio.AdenineIo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
