# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import did_pb2 as did__pb2


class DidStub(object):
  """The did sidechain service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Sign = channel.unary_unary(
        '/did.Did/Sign',
        request_serializer=did__pb2.ApiRequest.SerializeToString,
        response_deserializer=did__pb2.ApiResponse.FromString,
        )


class DidServicer(object):
  """The did sidechain service definition.
  """

  def Sign(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DidServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Sign': grpc.unary_unary_rpc_method_handler(
          servicer.Sign,
          request_deserializer=did__pb2.ApiRequest.FromString,
          response_serializer=did__pb2.ApiResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'did.Did', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
