# Generated by Django 2.2.8 on 2019-12-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_userapikeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServiceSessionVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=64)),
                ('api_key', models.CharField(max_length=64)),
                ('mnemonic_mainchain', models.CharField(max_length=300)),
                ('private_key_mainchain', models.CharField(max_length=300)),
                ('public_key_mainchain', models.CharField(max_length=300)),
                ('address_mainchain', models.CharField(max_length=64)),
                ('private_key_did', models.CharField(max_length=300)),
                ('public_key_did', models.CharField(max_length=300)),
                ('address_did', models.CharField(max_length=64)),
                ('did_did', models.CharField(max_length=64)),
                ('address_eth', models.CharField(max_length=64)),
                ('private_key_eth', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAPIKeys',
        ),
    ]
