# Generated by Django 2.2.8 on 2020-01-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20191225_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='user_files'),
        ),
    ]
