# Generated by Django 2.2.10 on 2020-04-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_savedfileinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedETHContractInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=64)),
                ('file_name', models.CharField(max_length=100)),
                ('contract_name', models.CharField(max_length=300)),
                ('contract_address', models.CharField(max_length=300)),
                ('contract_code_hash', models.CharField(max_length=300)),
            ],
        ),
    ]
