// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sidechain_eth.proto

package sidechain_eth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message
type Request struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Input                string   `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_21eaa0627d5e5698, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *Request) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Request) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

// The response message
type Response struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	StatusMessage        string   `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_21eaa0627d5e5698, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *Response) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*Request)(nil), "sidechain_eth.Request")
	proto.RegisterType((*Response)(nil), "sidechain_eth.Response")
}

func init() { proto.RegisterFile("sidechain_eth.proto", fileDescriptor_21eaa0627d5e5698) }

var fileDescriptor_21eaa0627d5e5698 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x09, 0x88, 0xa4, 0x9c, 0x28, 0x82, 0x03, 0xb5, 0x11, 0x13, 0x8a, 0x84, 0xc4, 0xd4,
	0x01, 0x1e, 0x01, 0xc2, 0x82, 0x58, 0xcc, 0xc0, 0x18, 0x99, 0x70, 0xc2, 0x56, 0xc1, 0x36, 0xb9,
	0x8b, 0x50, 0x1e, 0x86, 0x77, 0x45, 0x8d, 0xdd, 0x21, 0x62, 0xec, 0xf8, 0x7d, 0xb6, 0x7f, 0xdf,
	0xfd, 0x70, 0xce, 0xf6, 0x9d, 0x5a, 0xa3, 0xad, 0x6b, 0x48, 0xcc, 0x2a, 0x74, 0x5e, 0x3c, 0xce,
	0x27, 0xb2, 0x52, 0x50, 0x28, 0xfa, 0xee, 0x89, 0x05, 0x97, 0x50, 0xe8, 0x60, 0x9b, 0x35, 0x0d,
	0x65, 0x76, 0x95, 0xdd, 0x1c, 0xa9, 0x5c, 0x07, 0xfb, 0x44, 0x03, 0x96, 0x50, 0x38, 0x92, 0x1f,
	0xdf, 0xad, 0xcb, 0xfd, 0xf1, 0x60, 0x8b, 0x78, 0x01, 0x87, 0xd6, 0x85, 0x5e, 0xca, 0x83, 0xd1,
	0x47, 0xa8, 0x34, 0xcc, 0x14, 0x71, 0xf0, 0x8e, 0x09, 0x17, 0x90, 0xfb, 0x5e, 0x36, 0x57, 0x52,
	0x66, 0x24, 0xbc, 0x86, 0x13, 0x16, 0x2d, 0x3d, 0x37, 0x5f, 0xc4, 0xac, 0x3f, 0x28, 0x45, 0xcf,
	0xa3, 0x7d, 0x8e, 0x72, 0xf3, 0x3c, 0x8a, 0xf1, 0x87, 0x99, 0x4a, 0x74, 0xfb, 0x9b, 0xc1, 0xf1,
	0xcb, 0x76, 0x91, 0x5a, 0x0c, 0x3e, 0xc2, 0xd9, 0x03, 0x85, 0x4f, 0x3f, 0xd4, 0x62, 0xee, 0xbd,
	0x93, 0x4e, 0xb7, 0x82, 0x8b, 0xd5, 0xb4, 0x81, 0xb4, 0xe9, 0xe5, 0xf2, 0x9f, 0x8f, 0xd3, 0x56,
	0x7b, 0x58, 0xc3, 0xe9, 0xab, 0x96, 0xd6, 0xec, 0x16, 0xf3, 0x96, 0x8f, 0x65, 0xdf, 0xfd, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x97, 0x3d, 0x37, 0x3b, 0x83, 0x01, 0x00, 0x00,
}
