// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package wallet

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message
type Request struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Input                string   `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *Request) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Request) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

// The response message
type Response struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	StatusMessage        string   `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *Response) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*Request)(nil), "wallet.Request")
	proto.RegisterType((*Response)(nil), "wallet.Response")
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor_b88fd140af4deb6f) }

var fileDescriptor_b88fd140af4deb6f = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xbf, 0x4a, 0xc0, 0x30,
	0x10, 0xc6, 0xad, 0x62, 0x5a, 0x8f, 0xfa, 0x87, 0x43, 0x34, 0x38, 0x49, 0x41, 0x70, 0x2a, 0x68,
	0x9f, 0x40, 0xc4, 0x49, 0x5d, 0x32, 0xe8, 0x58, 0x22, 0x1c, 0x12, 0x5a, 0x9b, 0xd8, 0x5c, 0x28,
	0x7d, 0x1e, 0x5f, 0x54, 0x9a, 0x44, 0x5c, 0x75, 0xfc, 0xfd, 0x2e, 0xdf, 0x25, 0x5f, 0xa0, 0x5e,
	0xf4, 0x38, 0x12, 0xb7, 0x6e, 0xb6, 0x6c, 0x51, 0x24, 0x6a, 0x14, 0x94, 0x8a, 0x3e, 0x03, 0x79,
	0xc6, 0x73, 0x28, 0xb5, 0x33, 0xfd, 0x40, 0xab, 0x2c, 0x2e, 0x8b, 0xeb, 0x03, 0x25, 0xb4, 0x33,
	0x8f, 0xb4, 0xa2, 0x84, 0x72, 0x22, 0x5e, 0xec, 0x3c, 0xc8, 0xdd, 0x38, 0xf8, 0x41, 0x3c, 0x85,
	0x7d, 0x33, 0xb9, 0xc0, 0x72, 0x2f, 0xfa, 0x04, 0x8d, 0x86, 0x4a, 0x91, 0x77, 0x76, 0xf2, 0x84,
	0x67, 0x20, 0x6c, 0xe0, 0xed, 0x48, 0xde, 0x99, 0x08, 0xaf, 0xe0, 0xc8, 0xb3, 0xe6, 0xe0, 0xfb,
	0x0f, 0xf2, 0x5e, 0xbf, 0x53, 0x5e, 0x7d, 0x98, 0xec, 0x73, 0x92, 0x5b, 0x3c, 0x89, 0x78, 0x43,
	0xa5, 0x32, 0xdd, 0x7e, 0x15, 0x20, 0x5e, 0x63, 0x03, 0xec, 0xa0, 0xbe, 0x9f, 0x49, 0x33, 0x65,
	0x3e, 0x6e, 0x73, 0xd1, 0xdc, 0xeb, 0xe2, 0xe4, 0x57, 0xa4, 0x47, 0x35, 0x3b, 0x78, 0x03, 0xf0,
	0x62, 0x68, 0xf9, 0x67, 0x24, 0x8f, 0x1f, 0x9e, 0xee, 0xfe, 0x14, 0x79, 0x13, 0xf1, 0xaf, 0xbb,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0xd9, 0x5b, 0x4f, 0x7b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletClient interface {
	CreateWallet(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	ViewWallet(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	RequestELA(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type walletClient struct {
	cc *grpc.ClientConn
}

func NewWalletClient(cc *grpc.ClientConn) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) CreateWallet(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/CreateWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) ViewWallet(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/ViewWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) RequestELA(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/RequestELA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
type WalletServer interface {
	CreateWallet(context.Context, *Request) (*Response, error)
	ViewWallet(context.Context, *Request) (*Response, error)
	RequestELA(context.Context, *Request) (*Response, error)
}

// UnimplementedWalletServer can be embedded to have forward compatible implementations.
type UnimplementedWalletServer struct {
}

func (*UnimplementedWalletServer) CreateWallet(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWallet not implemented")
}
func (*UnimplementedWalletServer) ViewWallet(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewWallet not implemented")
}
func (*UnimplementedWalletServer) RequestELA(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestELA not implemented")
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/CreateWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).CreateWallet(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_ViewWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).ViewWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/ViewWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).ViewWallet(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_RequestELA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).RequestELA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/RequestELA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).RequestELA(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWallet",
			Handler:    _Wallet_CreateWallet_Handler,
		},
		{
			MethodName: "ViewWallet",
			Handler:    _Wallet_ViewWallet_Handler,
		},
		{
			MethodName: "RequestELA",
			Handler:    _Wallet_RequestELA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}
